/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DataEntryRouteImport } from './routes/data-entry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscribersIdRouteImport } from './routes/subscribers.$id'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntryRoute = DataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersIdRoute = SubscribersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscribersRoute,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/login'
    | '/subscribers'
    | '/templates'
    | '/groups/$id'
    | '/subscribers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/login'
    | '/subscribers'
    | '/templates'
    | '/groups/$id'
    | '/subscribers/$id'
  id:
    | '__root__'
    | '/'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/login'
    | '/subscribers'
    | '/templates'
    | '/groups/$id'
    | '/subscribers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataEntryRoute: typeof DataEntryRoute
  DispatchRoute: typeof DispatchRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubscribersRoute: typeof SubscribersRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-entry': {
      id: '/data-entry'
      path: '/data-entry'
      fullPath: '/data-entry'
      preLoaderRoute: typeof DataEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers/$id': {
      id: '/subscribers/$id'
      path: '/$id'
      fullPath: '/subscribers/$id'
      preLoaderRoute: typeof SubscribersIdRouteImport
      parentRoute: typeof SubscribersRoute
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
  }
}

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface SubscribersRouteChildren {
  SubscribersIdRoute: typeof SubscribersIdRoute
}

const SubscribersRouteChildren: SubscribersRouteChildren = {
  SubscribersIdRoute: SubscribersIdRoute,
}

const SubscribersRouteWithChildren = SubscribersRoute._addFileChildren(
  SubscribersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataEntryRoute: DataEntryRoute,
  DispatchRoute: DispatchRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LoginRoute: LoginRoute,
  SubscribersRoute: SubscribersRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
