/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpiSettingsRouteImport } from './routes/upi-settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DataEntryRouteImport } from './routes/data-entry'
import { Route as ChitsyncRouteImport } from './routes/chitsync'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscribersIdRouteImport } from './routes/subscribers.$id'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as CommunicationsRemindersRouteImport } from './routes/communications.reminders'
import { Route as CommunicationsReceiptsRouteImport } from './routes/communications.receipts'
import { Route as CommunicationsOffersRouteImport } from './routes/communications.offers'

const UpiSettingsRoute = UpiSettingsRouteImport.update({
  id: '/upi-settings',
  path: '/upi-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntryRoute = DataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ChitsyncRoute = ChitsyncRouteImport.update({
  id: '/chitsync',
  path: '/chitsync',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersIdRoute = SubscribersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscribersRoute,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)
const CommunicationsRemindersRoute = CommunicationsRemindersRouteImport.update({
  id: '/communications/reminders',
  path: '/communications/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsReceiptsRoute = CommunicationsReceiptsRouteImport.update({
  id: '/communications/receipts',
  path: '/communications/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsOffersRoute = CommunicationsOffersRouteImport.update({
  id: '/communications/offers',
  path: '/communications/offers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chitsync': typeof ChitsyncRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/upi-settings': typeof UpiSettingsRoute
  '/communications/offers': typeof CommunicationsOffersRoute
  '/communications/receipts': typeof CommunicationsReceiptsRoute
  '/communications/reminders': typeof CommunicationsRemindersRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chitsync': typeof ChitsyncRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/upi-settings': typeof UpiSettingsRoute
  '/communications/offers': typeof CommunicationsOffersRoute
  '/communications/receipts': typeof CommunicationsReceiptsRoute
  '/communications/reminders': typeof CommunicationsRemindersRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chitsync': typeof ChitsyncRoute
  '/data-entry': typeof DataEntryRoute
  '/dispatch': typeof DispatchRoute
  '/groups': typeof GroupsRouteWithChildren
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/upi-settings': typeof UpiSettingsRoute
  '/communications/offers': typeof CommunicationsOffersRoute
  '/communications/receipts': typeof CommunicationsReceiptsRoute
  '/communications/reminders': typeof CommunicationsRemindersRoute
  '/groups/$id': typeof GroupsIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/chitsync'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/import'
    | '/login'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/upi-settings'
    | '/communications/offers'
    | '/communications/receipts'
    | '/communications/reminders'
    | '/groups/$id'
    | '/subscribers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/chitsync'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/import'
    | '/login'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/upi-settings'
    | '/communications/offers'
    | '/communications/receipts'
    | '/communications/reminders'
    | '/groups/$id'
    | '/subscribers/$id'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/chitsync'
    | '/data-entry'
    | '/dispatch'
    | '/groups'
    | '/import'
    | '/login'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/upi-settings'
    | '/communications/offers'
    | '/communications/receipts'
    | '/communications/reminders'
    | '/groups/$id'
    | '/subscribers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ChitsyncRoute: typeof ChitsyncRoute
  DataEntryRoute: typeof DataEntryRoute
  DispatchRoute: typeof DispatchRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SubscribersRoute: typeof SubscribersRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  UpiSettingsRoute: typeof UpiSettingsRoute
  CommunicationsOffersRoute: typeof CommunicationsOffersRoute
  CommunicationsReceiptsRoute: typeof CommunicationsReceiptsRoute
  CommunicationsRemindersRoute: typeof CommunicationsRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upi-settings': {
      id: '/upi-settings'
      path: '/upi-settings'
      fullPath: '/upi-settings'
      preLoaderRoute: typeof UpiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-entry': {
      id: '/data-entry'
      path: '/data-entry'
      fullPath: '/data-entry'
      preLoaderRoute: typeof DataEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chitsync': {
      id: '/chitsync'
      path: '/chitsync'
      fullPath: '/chitsync'
      preLoaderRoute: typeof ChitsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers/$id': {
      id: '/subscribers/$id'
      path: '/$id'
      fullPath: '/subscribers/$id'
      preLoaderRoute: typeof SubscribersIdRouteImport
      parentRoute: typeof SubscribersRoute
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/communications/reminders': {
      id: '/communications/reminders'
      path: '/communications/reminders'
      fullPath: '/communications/reminders'
      preLoaderRoute: typeof CommunicationsRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications/receipts': {
      id: '/communications/receipts'
      path: '/communications/receipts'
      fullPath: '/communications/receipts'
      preLoaderRoute: typeof CommunicationsReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications/offers': {
      id: '/communications/offers'
      path: '/communications/offers'
      fullPath: '/communications/offers'
      preLoaderRoute: typeof CommunicationsOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface SubscribersRouteChildren {
  SubscribersIdRoute: typeof SubscribersIdRoute
}

const SubscribersRouteChildren: SubscribersRouteChildren = {
  SubscribersIdRoute: SubscribersIdRoute,
}

const SubscribersRouteWithChildren = SubscribersRoute._addFileChildren(
  SubscribersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ChitsyncRoute: ChitsyncRoute,
  DataEntryRoute: DataEntryRoute,
  DispatchRoute: DispatchRoute,
  GroupsRoute: GroupsRouteWithChildren,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SubscribersRoute: SubscribersRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  UpiSettingsRoute: UpiSettingsRoute,
  CommunicationsOffersRoute: CommunicationsOffersRoute,
  CommunicationsReceiptsRoute: CommunicationsReceiptsRoute,
  CommunicationsRemindersRoute: CommunicationsRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
